name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache de dependências
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Instalar dependências
        run: npm install

      - name: Rodar Lint
        run: npm run lint
        continue-on-error: true

      - name: Build
        run: npm run build
        continue-on-error: true

      - name: Rodar testes
        run: npm test